rootProject.name = "exchange"
include("admin-api")
include("core")
include("testing")
include("testing:fix")
include("fix-gateway")
include("market-data")
include("infra")
include("rest-api")
include("trading-ui")
include("admin-ui")
include("config")
